### ISSUE TITLE
Error handling for styloscope.ipynb's Gradio Page 

### ISSUE THREAD

**Issue by Sohammhatre10** [LemmensJens/CLARIAH-stylo#1]
1. <img width="939" alt="image" src="https://github.com/user-attachments/assets/5adeb727-1616-40c1-9867-58bc877a1b0a">
2. <img width="939" alt="image" src="https://github.com/user-attachments/assets/a4ea5c64-8da0-4d68-853b-859ce87e197f">
3. <img width="940" alt="image" src="https://github.com/user-attachments/assets/d2b81775-d3e2-4b2c-8233-1eb975563482">

(1) When the Gradio page loads for the first time STTR is accompanied with the column STTR token span.
(2) There is **no error handling for the case when the Lexical Diversity Metric is anything other than STTR for which the STTR Token span vanishes by throwing a connection error message**, so error handling is required here for Lexical Diversity Metric isn't STTR the dropdown for STTR token span must not load without throwing a connection error. 
(3) **When switching back to STTR the STTR Token span dropdown doesn't load along with it**.

**Comment by Sohammhatre10** [comment]
The issue is from Gradio's side will be raising this on their Issues panel, maybe due to the overloading of websockets on their side.

**Comment by Sohammhatre10** [comment]
Have corrected this here 
[https://github.com/clips/styloscope/pull/2](https://github.com/clips/styloscope/pull/2)

**Comment by LemmensJens** [comment]
Thank you for notifying us. Upgrading gradio leads to a number of dependency errors (primarily incompatibilities with SpaCy). Alternatively, downgrading fastapi - [suggested here](https://github.com/jhj0517/Whisper-WebUI/issues/258) - seems to work after a quick test. I adjusted this in the requirements.txt.

**Comment by Sohammhatre10** [comment]
I checked it using Gradio 4.43.0 was working gradio response was working well with but nevertheless glad to have helped you here.:)
